<?php

namespace BrightleafDigital\Api;

use BrightleafDigital\Exceptions\ApiException;
use BrightleafDigital\Exceptions\RateLimitException;
use BrightleafDigital\Exceptions\ValidationException;
use BrightleafDigital\Http\HttpClientInterface;

/**
 * Service class for Stories API endpoints.
 *
 * Stories are generated by the Asana system whenever users take actions such as
 * commenting or changing a task's assignee or section.
 *
 * @see https://developers.asana.com/reference/stories
 */
class StoriesApiService extends BaseApiService
{
    /**
     * Get a story
     * GET /stories/{story_gid}
     * Returns the full record for a single story.
     * API Documentation: https://developers.asana.com/reference/getstory
     *
     * @param string $storyGid Globally unique identifier for the story.
     * @param array $options Optional parameters to customize the request:
     * - opt_fields (string): A comma-separated list of fields to include in the response.
     * - opt_pretty (bool): Returns formatted JSON if true.
     *
     * @param int $responseType The type of response to return:
     * - HttpClientInterface::RESPONSE_FULL (1): Full response with status, headers, etc.
     * - HttpClientInterface::RESPONSE_NORMAL (2): Complete decoded JSON body.
     * - HttpClientInterface::RESPONSE_DATA (3): Only the data subset (default).
     *
     * @return array The response data based on the specified response type.
     * @throws ApiException
     * @throws RateLimitException
     * @throws ValidationException
     */
    public function getStory(
        string $storyGid,
        array $options = [],
        int $responseType = HttpClientInterface::RESPONSE_DATA
    ): array {
        $this->validateGid($storyGid, 'Story GID');

        return $this->getResource('stories', $storyGid, $options, $responseType);
    }

    /**
     * Update a story
     * PUT /stories/{story_gid}
     * Updates the story and returns the full record for the updated story.
     * Only comment stories can have their text updated, and only comment stories and attachment stories can be pinned.
     * Only one of `text` and `html_text` can be specified.
     * API Documentation: https://developers.asana.com/reference/updatestory
     *
     * @param string $storyGid Globally unique identifier for the story.
     * @param array $data The properties of the story to update. Can include:
     * - text (string): The plain text of the comment to update.
     * - html_text (string): The rich text of the comment to update.
     * - is_pinned (bool): Whether the story should be pinned to the top of the task.
     *
     * @param array $options Optional parameters to customize the request.
     * @param int $responseType The type of response to return.
     * @return array The response data based on the specified response type.
     * @throws ApiException
     * @throws RateLimitException
     * @throws ValidationException
     */
    public function updateStory(
        string $storyGid,
        array $data,
        array $options = [],
        int $responseType = HttpClientInterface::RESPONSE_DATA
    ): array {
        $this->validateGid($storyGid, 'Story GID');

        return $this->updateResource('stories', $storyGid, $data, $options, $responseType);
    }

    /**
     * Delete a story
     * DELETE /stories/{story_gid}
     * Deletes a story. A user can only delete stories they have created.
     * API Documentation: https://developers.asana.com/reference/deletestory
     *
     * @param string $storyGid Globally unique identifier for the story.
     * @param int $responseType The type of response to return.
     * @return array The response data based on the specified response type.
     * @throws ApiException
     * @throws RateLimitException
     * @throws ValidationException
     */
    public function deleteStory(
        string $storyGid,
        int $responseType = HttpClientInterface::RESPONSE_DATA
    ): array {
        $this->validateGid($storyGid, 'Story GID');

        return $this->deleteResource('stories', $storyGid, $responseType);
    }

    /**
     * Get stories from a task
     * GET /tasks/{task_gid}/stories
     * Returns the compact records for all stories on the task.
     * API Documentation: https://developers.asana.com/reference/getstoriesfortask
     *
     * @param string $taskGid The task to operate on.
     * @param array $options Optional parameters to customize the request:
     * - limit (int): Results per page.
     * - offset (string): Offset token for pagination.
     * - opt_fields (string): A comma-separated list of fields to include in the response.
     *
     * @param int $responseType The type of response to return.
     * @return array The response data based on the specified response type.
     * @throws ApiException
     * @throws RateLimitException
     * @throws ValidationException
     */
    public function getStoriesForTask(
        string $taskGid,
        array $options = [],
        int $responseType = HttpClientInterface::RESPONSE_DATA
    ): array {
        $this->validateGid($taskGid, 'Task GID');

        return $this->getResources("tasks/$taskGid/stories", $options, $responseType);
    }

    /**
     * Create a story on a task
     * POST /tasks/{task_gid}/stories
     * Adds a story to a task. This endpoint currently only allows for comment stories to be created.
     * API Documentation: https://developers.asana.com/reference/createstoryfortask
     *
     * @param string $taskGid The task to operate on.
     * @param array $data The properties of the story to create. Can include:
     * - text (string): The plain text of the comment to add.
     * - html_text (string): The rich text of the comment to add.
     * - is_pinned (bool): Whether the story should be pinned to the top of the task.
     *
     * @param array $options Optional parameters to customize the request.
     * @param int $responseType The type of response to return.
     * @return array The response data based on the specified response type.
     * @throws ApiException
     * @throws RateLimitException
     * @throws ValidationException
     */
    public function createStoryForTask(
        string $taskGid,
        array $data,
        array $options = [],
        int $responseType = HttpClientInterface::RESPONSE_DATA
    ): array {
        $this->validateGid($taskGid, 'Task GID');
        $this->validateAtLeastOneField($data, ['text', 'html_text'], 'Create Story');

        return $this->createResource("tasks/$taskGid/stories", $data, $options, $responseType);
    }
}
